export const SOURCES = [
    {
        id: 1,
        code: "vi",
        name: "vietnamese",
        content:
            "mùa thu mang giấc mơ quay về vẫn nguyên vẹn như hôm nào lá bay theo gió xôn xao chốn xưa em chờ chốn xưa em chờ đoạn đường ngày nào nơi ta từng đón đưa còn vấn vương không phai mờ giấu yêu thương trong vần thơ chúng ta là áng mây bên trời vội vàng ngang qua chúng ta chẳng thể nâng niu những câu thề cứ như vậy thôi không một lời lặng lẽ thế chia xa chiều mưa bên hiên vắng buồn còn ai thương ai mong ai điều anh luôn giữ kín trong tim thương em đôi mắt ướt nhòa điều anh luôn giữ kín trong tim này thương em đâu đó khóc òa điều anh luôn giữ kín trong tim này ngày mai nắng gió sương hao gầy có ai thương lắng lo cho em điều anh luôn giữ kín trong tim thương em anh mãi xin là điều anh luôn giữ kín trong tim này thương em vì thương thôi mà điều anh luôn giữ kín trong tim này dù cho nắng tắt xuân thay màu héo khô đi tháng năm xưa kia anh nguyện ghi mãi trong tim nắng vương trên cành héo khô những kỉ niệm xưa kia ngày mai người luyến lưu về giấc mơ từng có liệu có ta có anh nơi đó không có anh nơi đó không liệu có ta chúng ta là áng mây bên trời vội vàng ngang qua chúng ta chẳng thể nâng niu những câu thề cứ như vậy thôi không một lời lặng lẽ thế chia xa chiều mưa bên hiên vắng buồn còn ai thương ai mong ai điều anh luôn giữ kín trong tim thương em đôi mắt ướt nhòa điều anh luôn giữ kín trong tim này thương em đâu đó khóc òa điều anh luôn giữ kín trong tim này ngày mai nắng gió sương hao gầy có ai thương lắng lo cho em điều anh luôn giữ kín trong tim thương em anh mãi xin là điều anh luôn giữ kín trong tim này thương em vì thương thôi mà điều anh luôn giữ kín trong tim này dù cho nắng tắt xuân thay màu héo khô đi tháng năm xưa kia anh nguyện ghi mãi trong tim",
    },
];
